### ISSUE TITLE
Arguments array validation and wildcards

### ISSUE THREAD

**Issue by ajanini** [rebing/graphql-laravel#716] opened 2021-02-25 20:15 UTC
### Versions:
- graphql-laravel Version: 5.1.4
- Laravel Version: 8.14.0
- PHP Version: 7.3.9

### Question:

I am using Laravel's [Same validation](https://laravel.com/docs/8.x/validation#rule-same) for a `InputType` class as follows:
```php

namespace App\GraphQL\InputObjects;

use App\Models\Image;
use App\Models\User;
use GraphQL;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\InputType;

class UserInput extends InputType
{
    protected $attributes = [
        'name' => 'UserInput',
        'description' => 'Input object for User models'
    ];

    public function fields(): array
    {
        return [

            // other rules omitted

            'password' => [
                'name' => 'password',
                'type' => Type::string(),
                'rules' => [
                    'string',
                    'nullable',
                    "same:data.*.passwordConfirmation",
                ],
            ],
            'passwordConfirmation' => [
                'name' => 'passwordConfirmation',
                'type' => Type::string(),
            ],

            // other rules omitted

        ];
    }
}
```

My mutation class has the following `args` method:
```php
public function args(): array
{
    return [
        'data' => [
            'name' => 'data',
            'type' => Type::listOf(GraphQL::type('UserInput')),
            'rules' => [
                'required',
            ],
        ],
    ];
}
```

And my GraphQL Query Variables is as follows (edited to show only the relevant fields):
```json
{
    "data": [
        {
            "password": "aa",
            "passwordConfirmation": "aa"
        },
        {
            "password": "bb",
            "passwordConfirmation": "bb"
        }
    ]
}
```

As [documented](https://laravel.com/docs/8.x/validation#validating-arrays), using the wildcard `*` to validate arrays should work on Laravel's end.
I ran a JSON POST request test and confirmed it does work outside the `graphql` endpoint.

I can't get it to work with the GraphQL mutation, however. It seems the wildcard is not being parsed (please note the `*` below).
The following error is returned, even when the `password` and `passwordConfirmation` fields are exactly the same:

```json
{
    "errors": [
        {
            "message": "validation",
            "locations": [
                {
                    "line": 4,
                    "column": 5
                }
            ],
            "validation": {
                "data.0.password": [
                    "The data.0.password and data.*.password must match."
                ]
            }
        }
    ],
    "data": {
        "CreateUserMutation": null
    }
}
```

I'm not sure if I'm doing something wrong, if this is simply not supported for GraphQL validation, or if this is a bug...

**Comment by crissi** [comment] 2021-02-25 23:02
have you tried?

'rules' => [
                    'string',
                    'nullable',
                    "same:passwordConfirmation",
                ]

**Comment by ajanini** [comment] 2021-02-26 11:16
Hi @crissi, thanks for your reply.

I have tried your suggestion, but the error message becomes:
`The data.0.password and password confirmation must match.`

**Comment by mfn** [comment] 2021-04-15 23:22
@ajanini where you able to solve it?

Still not sure if there's a bug somewhere or improper use of the feature 😅

I rarely have a need for the wildcard, the one time I used it in a project like `field.*` (but no further level, like in your example), there were no issues.

If you still have the problem, I think it would be best to make a PR with tests showing the problem, then _maybe_ ("maybe") working on a potential fix is easier.

---
Off-topic:

> passwordConfirmation

Fun fact: I always wondered why an _API_ should have this. Isn't this a "human" thing rather and should just be checked in the browser and doesn't need to be sent/checked on the server? 🤷‍♀️

**Comment by ajanini** [comment] 2021-04-16 09:34
Hi @mfn.

No I was not able to solve it.

I don't think I'll be able to make a PR anytime soon, but I'll try.

---

I agree with your `passwordConfirmation` point, BTW.

**Comment by mfn** [comment] 2021-04-16 17:48
> I don't think I'll be able to make a PR anytime soon, but I'll try.

No worries, given you descriptions I tried to recreate your case in https://github.com/rebing/graphql-laravel/pull/746 and I think I was able to produce what you see.

I think I know what the problem is, though no idea yet how to fix it. The validation is done in this part https://github.com/rebing/graphql-laravel/blob/8b156d5b98dee7e3fb86c62f42253a1d647de288/src/Support/Field.php#L180-L188

`getRules()` returns this shape:
```php
            [
                'data' =>
                    [
                        0 => 'required',
                    ],
                'data.0.password' =>
                    [
                        0 => 'string',
                        1 => 'nullable',
                        2 => 'same:data.*.password_confirmation',
                    ],
            ]
```
The key `data.0.password` is the problem: it should be `data.*.password`.

To proof this, I changed the references code to this and then it was correctly working:
```php
            if (count($rules)) {
                $rules['data.*.password'] = $rules['data.0.password'];
                unset($rules['data.0.password']);

                $validator = $this->getValidator($args, $rules);
```

Further when you provide _multiple_ inputs, the "rules" start to look like this:
```php
            [
                'data' => [
                    0 => 'required',
                ],
                'data.0.password' => [
                    0 => 'string',
                    1 => 'nullable',
                    2 => 'same:data.*.password_confirmation',
                ],
                'data.1.password' => [
                    0 => 'string',
                    1 => 'nullable',
                    2 => 'same:data.*.password_confirmation',
                ],
            ];
```

---
I'm really not sure if this is properly fixable. Might be just a limitation.

Don't forget that adding `'rules'` this way on your GraphQL types is just "sugar on top": nothing prevents you from creating rules in the mutations `resolve()` methods where you also receive the whole input in `$args`, in which case you've all the freedom how to write your rules.

@crissi or do you think this is fixable? 🤔

**Comment by ajanini** [comment] 2021-04-16 18:29
Wow @mfn this is awesome!

Thanks a lot for looking into it.

I did try to apply the rules in the `resolve()` method, but the error returned looked different than the one using `'rules'` in the `InputType`. I don't know if I did it correctly, however.

I wish I could help you guys figure this out, but it is evidently beyond my abilities. If you think there's anything I can help with, please let me know.

**Comment by mfn** [comment] 2021-04-16 18:47
This resolver should do it:
```php
    public function resolve($root, $args): bool
    {
        $validator = \Illuminate\Support\Facades\Validator::make($args, [
            'data.*.password' => 'string|nullable|same:data.*.password_confirmation',
        ]);

        if ($validator->fails()) {
            throw new \Rebing\GraphQL\Error\ValidationError('validation', $validator);
        }
```
I guess the trick is to know (but how? it's not documented) to throw this particular exception so that the error response matches the usual ones.

I will look into it why throwing `\Illuminate\Validation\ValidationException` couldn't do the same, because then it would come down to:
```php
        $validator = \Illuminate\Support\Facades\Validator::make($args, [
            'data.*.password' => 'string|nullable|same:data.*.password_confirmation',
        ])->validate();
```

**Comment by mfn** [comment] 2021-04-16 21:54
I've just merged https://github.com/rebing/graphql-laravel/pull/748 , so with the **next** release it will be possible to handle the validation in resolver like this:
```php
protected function resolve($root, array $args) {
    \Illuminate\Support\Facades\Validator::make($args, [
        'data.*.password' => 'string|nullable|same:data.*.password_confirmation',
    ])->validate();
}
```
as Laravels `ValidationException` will be automatically converted in the same error format as the internal `ValidationError`

**Comment by mfn** [comment] 2021-04-16 22:07
You can also define a `rules()` method on the _mutation_, which works in a similar fashion as the per-field `'rule'`, though it's almost as you would use a custom validation in the resolver, see https://github.com/rebing/graphql-laravel#adding-validation-to-a-mutation
> Alternatively, you can add a method to define the validation rules that apply, giving you more freedom on composing the rules (e.g. multi-field validations).

In your case (after removing the `'rules'` on `UserInput`), add this to your mutation:
```php
    protected function rules(array $args = []): array
    {
        return [
            'data.*.password' => [
                'string',
                'nullable',
                'same:data.*.password_confirmation',
            ],
        ];
    }
```

---
I believe we covered now all the grounds here 😅, let me know if this works for your!

**Comment by illambo** [comment] 2021-04-17 05:47
Hello everyone, I hope to center the discussion because I had not followed it before (in case excuse me).
Usually I use this approach, maybe it can be useful or give some other ideas.

```php
// input

/**
 * Class MeInput.
 */
class MeInput extends InputType
{
    /** @var string */
    public const NAME = 'MeInput';

    /** @var string[] */
    protected $attributes = [
        'name' => self::NAME,
        'description' => 'An me input',
    ];

    /**
     * @return array
     */
    public function fields(): array
    {
        return [
            'name' => [
                'type' => Type::string(),
                'description' => 'The name',
            ],
        ];
    }

    /**
     * @param  array<string,mixed>  $args
     * @return array<string,mixed>
     */
    public static function creationRules(array $args = []): array
    {
        return [
            'name' => [
                'filled',
                'string',
                'max:255',
            ],
        ];
    }

    /**
     * @param  array<string,mixed>  $args
     * @return array<string,mixed>
     */
    public static function updateRules(array $args = []): array
    {
        return [
            'name' => [
            	'sometimes',
                'filled',
                'string',
                'max:255',
            ],
        ];
    }

    /**
     * @param  array<string,mixed>  $input
     * @return array<string,mixed>
     */
    public static function parse(array $input = []): array
    {
        $data = [];

        if (array_key_exists('name', $input)) {
            $data['name'] = $input['name'];
        }
        
        return $data;
    }
}

// mutation

class UpdateMeMutation extends Mutation
{
    /** @var string */
    public const NAME = 'updateMe';

    /**
     * @var User|null
     */
    protected $model;

    /**
     * @var array
     */
    protected $attributes = [
        'name' => self::NAME,
        'description' => 'A update me mutation',
    ];

    /**
     * @return Type
     */
    public function type(): Type
    {
        return GraphQL::type(UserType::NAME);
    }

    /**
     * @return array
     */
    public function args(): array
    {
        return [
            'input' => [
                'name' => 'input',
                'type' => Type::nonNull(GraphQL::type(MeInput::NAME)),
            ],
        ];
    }

    /**
     * @param  mixed  $root
     * @param  array  $args
     * @param  mixed  $ctx
     * @param  ResolveInfo|null  $resolveInfo
     * @param  Closure|null  $getSelectFields
     * @return bool
     * @throws AuthorizationError
     */
    public function authenticate($root, array $args, $ctx, ResolveInfo $resolveInfo = null, Closure $getSelectFields = null): bool
    {
        //$this->performCommonAuthorizeChecks();

        $this->model = auth()->user();

        return true;
    }

    /**
     * @param array<string,mixed> $args
     * @return array<string,mixed>
     */
    protected function rules(array $args = []): array
    {
        return array_merge(prefix_array_keys('input.', MeInput::updateRules($args)), [
        	'input' => [
                'present',
            ], 
            // extra rules for the mutation ..
        ]);
    }

    /**
     * @param $root
     * @param $args
     * @param $context
     * @param  ResolveInfo  $resolveInfo
     * @param  Closure  $getSelectFields
     * @return User|null
     */
    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        /** @var SelectFields $fields */
        $fields = $getSelectFields();
        //$select = $fields->getSelect();
        $with = $fields->getRelations();

        $input = data_get($args, 'input', null);
        $data = $this->parse($input);

        // ..

        return $this->model;
    }

    /**
     * @param $input
     * @return array
     */
    protected function parse($input)
    {
        return MeInput::parse($input);
    }
}

// helper

if (! function_exists('prefix_array_keys')) {
    /**
     * @param  string  $prefix
     * @param  array  $array
     * @return array
     */
    function prefix_array_keys(string $prefix, array $array): array
    {
        return array_combine(array_map(function ($key) use ($prefix) {
            return $prefix.$key;
        }, array_keys($array)), $array);
    }
}
```

I use this approach because the same input can be called by different queries so in this way I can "shape" it.
Perhaps in your case it would be possible to inject the information into the static method and then build the rule properly.

```php
protected function rules(array $args = []): array
{
    $prefix = 'input.';
    return array_merge(prefix_array_keys($prefix, MeInput::rules($args, $prefix)), []);
}

public static function rules(array $args = [], ?$prefix = null): array
{
	// now u can u prefix ... 

    return [
        // ..
    ];
}
```

What do you think?

**Comment by mfn** [comment] 2021-04-17 20:54
I've rewritten the docs about Validation, I hope they're more clear now: https://github.com/rebing/graphql-laravel#validation

I think this is all we can do here for now, therefore closing the issue; otherwise let me know if you've more questions.

**Closed by mfn** 2021-04-17 20:54 UTC
Labels: help wanted, question
