### ISSUE TITLE
How to get a custom header in the resolve method of rebing/graphql-laravel package in graphql?

### ISSUE THREAD

**Issue by hardikpanotmc** [rebing/graphql-laravel#929] opened 2022-07-13 05:09 UTC
### Versions:
- graphql-laravel Version: ^8.3
- Laravel Version: 8.75
- PHP Version: 7.4

### Description:

I am creating graphql in laravel. I was use rebing/graphql-laravel package( #link here ). I want to get a custom header in the resolve method of query/mutation.

I want my header in the resolve method anyone has an idea about this then help me.

### Steps To Reproduce:

Need header access in the resolve method.

**Comment by mfn** [comment] 2022-07-13 08:07
Duplicate of https://github.com/rebing/graphql-laravel/discussions/928

**Closed by mfn** 2022-07-13 08:07 UTC
Labels: bug
