### ISSUE TITLE
Problems with interfaces

### ISSUE THREAD

**Issue by tricky666** [rebing/graphql-laravel#20] opened 2017-06-29 18:26 UTC
I have a problem accessing fields in types implementing an interface. 
I have a simple interface 'TestInterface' defining fields type and field1. I have an object TestObject implementing the interface and defining the fields type, field1 and field2.

I have a simple query returning a list of TestInterface type objects.

The schema generates correctly and looks fine (inspecting in graphiql).

I do a simple query to confirm that types are being resolved correctly:

{
  Tests{
    __typename
    field1
  }
}

which is confirmed in result:

{
  "data": {
    "Tests": [
      {
        "__typename": "TestObject",
        "field1": "asd"
      },...
    ]
  }
}

However if I try to query field2, which is defined on TestObject (but not in the interface):

{
  Tests{
    __typename
    field1
    ... on TestObject {field2}
  }
}

I get the following: Field "field2" is not defined for type "TestInterface\"

So even though the first query confirms that the return is of concrete type TestObject, for some reason it tries to resolve field2 on TestInterface.

**Comment by rebing** [comment] 2017-06-29 18:35
I haven't tried using interfaces with GraphQL, so I'm not sure how it sould work. How do you define the fields separately (outside the `fields` function) to be implemented? Could you please show me code of the class and interface.

**Comment by tricky666** [comment] 2017-06-29 18:44
I made a simple example to demonstrate. There's nothing fancy going on when resolving individual fields:

interface:
`class TestInterface extends InterfaceType {

    protected $attributes = [
        'name' => 'TestInterface',
        'description' => 'Test interface',
    ];

    public function fields()
    {
        return [
            # Fields
            'type' => [
                'type' => Type::string(),
                'description' => 'the type',
            ],
            'field1' => [
                'type' => Type::string(),
                'description' => 'field 1',
            ]
        ];
    }

    public function resolveType($root) {
        return GraphQL::type('TestObject');
    }
}`
Test type:
`class TestObject extends GraphQLType {

    protected $attributes = [
        'name'          => 'TestObject',
        'description'   => 'A test object',
        'model'         => Test::class,
    ];

    public function fields()
    {
        return [
            # Fields
            'type' => [
                'type' => Type::string(),
                'description' => 'the type',
            ],
            'field1' => [
                'type' => Type::string(),
                'description' => 'field1',
            ],
            'field2' => [
                'type' => Type::string(),
                'description' => 'field2',
            ]
        ];
    }

    public function interfaces() {
        return [
            GraphQL::type('TestInterface')
        ];
    }
}`

**Comment by tricky666** [comment] 2017-06-29 19:01
Just a quick note I tried switching to the Folklore package which your version is based on at it runs fine on that, so it looks like there is a bug here.

**Comment by rebing** [comment] 2017-06-30 12:04
Ah, I didn't even remember the `interfaces` function was a possibility. I will try to find the time to look into it over the weekend.

**Comment by rebing** [comment] 2017-07-03 08:48
I couldn't currently find the bug and unfortunately don't have too much spare time to deal with this. But if you can figure it out, feel free to submit a PR :)

**Comment by RSchwan** [comment] 2017-07-05 09:15
I digged a bit into the code and it seems the problem is in the `SelectFields` class. It tries to fetch all selectable fields but it only knows it's from type `TestInterface`. It tries to find the field `field2` but can't find it because the interface isn't yet resolved to `TestObject`.
I think it can be fixed by selecting all fields of possible casts (i.e. `... on TestObject`).
But I don't know if such a function exists to get all possible cast.

**Closed** 2017-08-04 11:56 UTC
