### ISSUE TITLE
Same relationship aliased fails to resolve

### ISSUE THREAD

**Issue by edgarsn** [rebing/graphql-laravel#717] opened 2021-02-26 13:37 UTC
### Versions:
- graphql-laravel Version: master branch
- PHP Version: 7.4.3

### Description:

Querying same relationship twice with alias fails. I wrote test for it.

### Steps To Reproduce:

<details>
  <summary>See test</summary>

```php
    public function testRelationshipQueryAlias(): void
    {
        /** @var User $user */
        $user = factory(User::class)->create();

        /** @var Post $postFlagged */
        $postFlagged = factory(Post::class)
            ->create([
                'flag' => true,
                'user_id' => $user->id,
            ]);

        /** @var Post $postNonflagged */
        $postNonflagged = factory(Post::class)
            ->create([
                'user_id' => $user->id,
            ]);

        $graphql = <<<'GRAQPHQL'
{
  users(select: true, with: true) {
    id
    name
    flagged: posts(flag: true) {
      body
      id
      title
    }
    nonflagged: posts(flag: false) {
      body
      id
      title
    }
  }
}
GRAQPHQL;

        $this->sqlCounterReset();

        $result = $this->httpGraphql($graphql);

        $expectedResult = [
            'data' => [
                'users' => [
                    [
                        'id' => (string) $user->id,
                        'name' => $user->name,
                        'flagged' => [
                            [
                                'body' => $postFlagged->body,
                                'id' => (string) $postFlagged->id,
                                'title' => $postFlagged->title,
                            ],
                        ],
                        'nonflagged' => [
                            [
                                'body' => $postNonflagged->body,
                                'id' => (string) $postNonflagged->id,
                                'title' => $postNonflagged->title,
                            ],
                        ],
                    ],
                ],
            ],
        ];
        $this->assertSame($expectedResult, $result);
    }
```
</details>

<details>
  <summary>See output</summary>

```
1) Rebing\GraphQL\Tests\Database\SelectFields\QueryArgsAndContextTests\NestedRelationLoadingTest::testRelationshipQueryAlias
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
             0 => Array &3 (
                 'id' => '1'
                 'name' => 'Kade Oberbrunner'
-                'flagged' => Array &4 (
-                    0 => Array &5 (
-                        'body' => 'Sed autem eum error fugit in quod.'
-                        'id' => '1'
-                        'title' => 'Mr.'
-                    )
-                )
-                'nonflagged' => Array &6 (
-                    0 => Array &7 (
-                        'body' => 'Provident explicabo distinctio illo rerum a exercitationem et.'
-                        'id' => '2'
-                        'title' => 'Miss'
-                    )
-                )
+                'flagged' => Array &4 ()
+                'nonflagged' => Array &5 ()
             )
         )
     )
 )
```
</details>

If i change query to: (basically removing `nonflagged`)

```
{
  users(select: true, with: true) {
    id
    name
    flagged: posts(flag: true) {
      body
      id
      title
    }
  }
}
```

... and change expected result to:

```php
$expectedResult = [
    'data' => [
        'users' => [
            [
                'id' => (string) $user->id,
                'name' => $user->name,
                'flagged' => [
                    [
                        'body' => $postFlagged->body,
                        'id' => (string) $postFlagged->id,
                        'title' => $postFlagged->title,
                    ],
                ],
            ],
        ],
    ],
];
```

test passes. Is it really a bug or am I missing something? :)

**Comment by edgarsn** [comment] 2021-02-26 15:01
After some research, Laravel doesn't support eager load relationship aliasing unfortunatelly (I didn't pay attention previously on that one). Without that I don't think this is even possible, isn't it?

**Comment by crissi** [comment] 2021-03-02 10:02
yes not possible easily, i made a hacked solution somewhere in closed prs. 

Should be easy when/if this get implemented: https://github.com/laravel/ideas/issues/2183

**Comment by mfn** [comment] 2021-04-05 21:53
I think @crissi is referring to https://github.com/rebing/graphql-laravel/pull/612 which was triggered by https://github.com/rebing/graphql-laravel/issues/604

Closing it for either a shortcoming we're not able to overcome and/or duplicate of https://github.com/rebing/graphql-laravel/issues/604

To OP: though I see you already made tests, I'm happy to include tests which assert the "undesired" state which in case in the future this gets fixed and those tests then break, serving as a reminder to update them.

**Closed by mfn** 2021-04-05 21:53 UTC
Labels: SelectFields, bug
