### ISSUE TITLE
Reusable Fields not acceptable as object argument

### ISSUE THREAD

**Issue by kirgy** [rebing/graphql-laravel#536] opened 2019-11-25 08:15 UTC
### Versions:
- graphql-laravel Version: 3.1
- Laravel Version: 5.8
- PHP Version: 7.2

### Question:
I'm trying to implement the Reusable Fields described here:
https://github.com/rebing/graphql-laravel#even-better-reusable-fields

But I'm getting the following error:
```Argument 2 passed to Rebing\\GraphQL\\Support\\Type::getFieldResolver() must be of the type array, object given, called in /var/www/vendor/rebing/graphql-laravel/src/Support/Type.php on line 95```

It's almost a copypasta of the example, but I'm uncertain if I'm doing something fundementally wrong here or if it is a bug?:

```php
<?php

namespace App\GraphQL\InputType\GuestLanding;

use App\GraphQL\Fields\DateTimeField;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\InputType;

class WeddingInformationInput extends InputType
{
    protected $attributes = [
        'name' => 'WeddingInformationInput',
        'description' => 'A wedding information input'
    ];

    public function fields(): array
    {
        return [
            'title' => [
                'name' => 'title',
                'type' => Type::nonNull(Type::string())
            ],
            'weddingDate' => new DateTimeField([
                    'alias' => 'wedding_date',
            ])
        ];
    }
}
```

```php
<?php

namespace App\GraphQL\Fields;

use Carbon\Carbon;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Field;

class DateTimeField extends Field
{
    protected $attributes = [
        'description' => 'A datetime',
    ];

    /**
     * DateTimeField constructor.
     * @param array $settings
     */
    public function __construct(array $settings = [])
    {
        $this->attributes = \array_merge($this->attributes, $settings);
    }

    /**
     * @return Type
     */
    public function type(): Type
    {
        return Type::string();
    }

    public function args(): array
    {
        return [
            'format' => [
                'type' => Type::string(),
                'defaultValue' => 'Y-m-d H:i',
                'description' => 'Defaults to Y-m-d H:i',
            ],
        ];
    }

    /**
     * @param $root
     * @param $args
     * @return String|null
     */
    protected function resolve($root, $args) : ?String
    {
        $date = $root->{$this->getProperty()};

        if (!$date instanceof Carbon) {
            return null;
        }

        return (string) Carbon::createFromFormat('Y-m-d H:i:s', $date)->format($args['format']);
    }

    /**
     * @return string|null
     */
    protected function getProperty()
    {
        return $this->attributes['alias'] ?? $this->attributes['name'];
    }
}

```

**Comment by mfn** [comment] 2019-11-25 15:05
I've a feeling this broke when I moved the library to 2.0.0 and added types everywhere and simply wasn't aware of this.

Can you check if "it works" if you just remove the `array` type declaration directly in the vendor/ files?

**Comment by kirgy** [comment] 2019-11-25 15:17
@mfn sure I'll check when I'm back at my machine this evening (GMT+0), I imagine that's the issue.

**Comment by kirgy** [comment] 2019-11-25 20:46
This solves that immediate problem but creates further down the line:

```
  "message": "Object of class App\\GraphQL\\Fields\\DateTimeField could not be converted to int",
  "exception": "ErrorException",
  "file": "/var/www/vendor/webonyx/graphql-php/src/Type/Definition/InputObjectType.php",
  "line": 84,
```

**Comment by mfn** [comment] 2019-11-25 20:48
Ok, thx. Was worth I shot.

**Comment by mfn** [comment] 2019-11-26 16:33
Maybe you can take a look at `\Rebing\GraphQL\Tests\Unit\InstantiableTypesTest\InstantiableTypesTest` and figure it out. It's supposed to cover this use case, e.g. `\Rebing\GraphQL\Tests\Unit\InstantiableTypesTest\UserType::fields` uses such definitions:
```php
        return [
            'id' => [
                'type' => Type::id(),
            ],
            'dateOfBirth' => new FormattableDate,
            'createdAt' => new FormattableDate([
                'alias' => 'created_at',
            ]),
        ];

```

**Comment by mfn** [comment] 2019-11-26 17:11
In `\Rebing\GraphQL\Support\Type::getFields` it's supposed to match in this condition:
```php
            } elseif ($field instanceof Field) {
                $field->name = $name;
                $allFields[$name] = $field->toArray();
            } elseif ($field instanceof FieldDefinition) {
```
but instead it hits this one:
```php
            } else {
                $resolver = $this->getFieldResolver($name, $field);
…
```
In your pasted example your class extends `\Rebing\GraphQL\Support\Field` so this looks good.

I suggest to fire up your debugger when resolving this type and track the flow in `\Rebing\GraphQL\Support\Type::getFields`

**Comment by thanhliem89dn** [comment] 2019-12-02 04:50
I think the reason is `FieldDefinition` in this condition is undefined ====>   `elseif ($field instanceof FieldDefinition)`

**Comment by thanhliem89dn** [comment] 2019-12-02 05:10
in `Rebing\GraphQL\Support\Field`, I saw that `Field` class is not extended from FieldDefinition so how `$field instanceof FieldDefinition` can work

**Comment by thanhliem89dn** [comment] 2019-12-02 05:31
It works if we convert `Field` class to `array`
> return [
            'id' => [
                'type' => Type::id(),
            ],
            'dateOfBirth' => (new FormattableDate)->toArray(),
            'createdAt' => (new FormattableDate([
                'alias' => 'created_at',
            ]))->toArray(),
        ];

**Comment by mfn** [comment] 2021-04-05 20:27
From https://github.com/rebing/graphql-laravel/issues/536#issuecomment-560228646
> I think the reason is this condition is false ====> `elseif ($field instanceof FieldDefinition)`

No, it's the line above which is supposed to match https://github.com/rebing/graphql-laravel/blob/28b6af4751e60807c07f91cf527ac88df9f0bfd9/src/Support/Type.php#L92-L95

The `$field instanceof Field` is important, `Field` referring to `\Rebing\GraphQL\Support\Field`.

Yes, the `->toArray()` works because this is essentially what happens in `\Rebing\GraphQL\Support\Type::getFields` but it should be done _automatically_.

I still can't reproduce this, my comment from https://github.com/rebing/graphql-laravel/issues/536#issuecomment-558728962 still stands

> I suggest to fire up your debugger when resolving this type and track the flow in `\Rebing\GraphQL\Support\Type::getFields`

I'm therefore closing this unless someone can bring up a reproducible example or a PR with tests for fixing this. The fastest way to go about this would probably be to use `\Rebing\GraphQL\Tests\Unit\InstantiableTypesTest\InstantiableTypesTest` as a start.

**Closed by mfn** 2021-04-05 20:27 UTC
Labels: question
