### ISSUE TITLE
Need support for Laravel 7.x 

### ISSUE THREAD

**Issue by zinnah1995** [rebing/graphql-laravel#610] opened 2020-03-25 21:44 UTC

**Comment by mfn** [comment] 2020-03-26 07:28
Duplicate of https://github.com/rebing/graphql-laravel/issues/600

Please use https://github.com/rebing/graphql-laravel/releases/tag/5.0.0-rc2 for now

**Closed by mfn** 2020-03-26 07:28 UTC
Labels: enhancement

**Comment by mfn** [comment] 2020-04-03 14:32
https://github.com/rebing/graphql-laravel/releases/tag/5.0.0 has been released with L7 support!
