### ISSUE TITLE
Add support for decorators for graphql query definitions

### ISSUE THREAD

**Issue by paulomunky1** [rebing/graphql-laravel#500] opened 2019-10-21 11:42 UTC
My app requires both "paginated" queries and "all results" queries for most of my models, resulting in a lot of code duplication 

Ideally I would like to be able to extend a class using the decorator pattern at run-time and update some properties of the class. 

Pagination is an example of why I think this would be useful

For example:

config/graphql

```
'schemas' => [
        'default' => [
            'query' => [
                'addresses'                    => App\GraphQL\Queries\Addresses::class,
                'paginated_addresses'  => App\GraphQL\Queries\Paginated\PaginatedAddresses::class,
            ]
        ]
    ]
```

Two separate classes are needed to return these queries. However the only difference between these two classes is the query type and some additional arguments for the paginated query. I use an AbstractQuery class to check whether the type is paginated, so I can deal with it accordingly in the resolve function

Having two classes means there is twice as much to maintain. Rather than duplicating the arguments and permissions in the paginated class, I currently create a trait as follows:

```
trait _PaginationTrait
{
    public function args(): array
    {
        return array_merge(parent::args(), [  
            'page'  => ['type' => Type::int()],
            'limit' => ['type' => Type::int()]
        ]);
    }

    public function type(): Type
    {
        return GraphQL::paginate($this->graphQlType());
    }

}
```

```
class PaginatedAddresses extends Addresses
{
    use _PaginationTrait;

    protected function graphQlType(): string
    {
    	return 'address';
    }
}
```

However I would prefer to use a decorator to apply these changes, so I don't have to create separate (almost identical) pagination classes. The decorator could be responsible for adding the extra arguments and changing the type

The only place I can see to do this is the config/graphql file, but it doesn't accept closures. 

(I don't think it is very good practice to add a closure to a config file, but thought I'd give it a try anyway)

eg. 

```
'schemas' => [
        'default' => [
            'query' => [
                'paginated_addresses' => function() {
                    return new PaginatedQuery(App\GraphQL\Queries\Addresses::class);
                }
            ]
        ]
    ]
```

Is there a way to apply a decorator at run time in the way that I am proposing? If not, would you consider adding this as a new feature?

Thanks
Paul

**Comment by itsmill3rtime** [comment] 2019-11-29 16:39
I made a Query class that i extend off of that extends off the BaseQuery to accomplish something similar. 

then on each query file i put 

protected $type = 'collection'; // model, collection, paginated



```
<?php

namespace App\GraphQL\Configuration;

use Closure;
use GraphQL\Type\Definition\ResolveInfo;
use Rebing\GraphQL\Support\Query as BaseQuery;

abstract class Query extends BaseQuery
{
    protected $builder;

    protected $model;

    protected $type = 'collection';// model, collection, paginated

    public function __construct()
    {
        if (!empty($this->model)) {
            $this->builder = $this->model::query();
        }
    }

    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        $fields = $getSelectFields();

        $this->scope($args);

        $this->filter($args);

        $this->sort($args);

        $this->builder->select($fields->getSelect());

        switch ($this->type) {
            case 'model':
                $model = $this->builder->first();

                if (!empty($model)) {
                    $model->loadMissing($fields->getRelations());
                }

                return $model;
                break;
            case 'collection':
                return $this->builder->with($fields->getRelations())->get();
            case 'paginated':
                return $this->builder
                    ->with($fields->getRelations())
                    ->paginate(data_get($args, 'limit', 25), ['*'], 'page', data_get($args, 'page', 1));
                break;
        }
    }
```

**Comment by mfn** [comment] 2020-01-19 16:07
I also don't think going forward with the closure idea in the config make sense.

I'm closing this issue not because I don't think it makes sense, but rather there's a lack of actionable here: a concrete technical proposal; which usually happens via PRs.

Feel free to add more ideas but as it stands, I don't see how anything moves forward here just because the issue is open.

**Closed by mfn** 2020-01-19 16:07 UTC
Labels: enhancement
