### ISSUE TITLE
Error when setting $attributes['query'] on a type

### ISSUE THREAD

**Issue by JakeBooher** [rebing/graphql-laravel#798] opened 2021-06-21 16:02 UTC
### Versions:
- graphql-laravel Version: 7.2.0
- Laravel Version: 8.33.1 
- PHP Version: 8.0.3

### Description:

If you set `model` on a GraphQL type's $attribute variable it will trigger errors if a function doesn't exist, even if there is a resolver to handle it when attempting to

```
Call to undefined method App\Models\User::avatar()
```

This is the `avatar` definition I have on my `UserType`:

```php
            'avatar' => [
                'type' => Type::nonNull(\GraphQL::type('Avatar')),
                'resolve' => function(User $user) {
                    $avatar = $user->avatar;

                    if (!isset($avatar['data']) || !isset($avatar['kind']) || $avatar['kind'] !== 'upload') {
                        $avatarData = AvatarUtil::getDefaultAvatarStyling($user->name);
                        return [
                            'kind' => 'default',
                            'data' => [
                                'kind' => 'default',
                                'bgColor' => $avatarData['bgColor'],
                                'textColor' => $avatarData['color'],
                                'text' => $avatarData['innerContent'],
                            ],
                        ];
                    } else {
                        $avatar['data']['kind'] = $avatar['kind'];
                    }

                    return $avatar;
                }
            ],
```

The relevant portion this happens is in \Rebing\GraphQL\Support\SelectFields on the `$relation = call_user_func([app($parentType->config['model']), $relationsKey]);` line. ( https://github.com/rebing/graphql-laravel/blob/master/src/Support/SelectFields.php#L201 ). This field is not a relation, and I'm currently not seeing a way to mark it as such so it doesn't try to handle it as if it were a relation

**Comment by mfn** [comment] 2021-06-21 21:10
- is it an actual column in the DB?
- or is it an attribute on your model?
- did you try `'selectable' => false` for that field?

**Comment by JakeBooher** [comment] 2021-06-23 14:33
1. It is a column on the DB
2. it is in the attributes array, and can be accessed with `$model->avatar`, but isn't a manually defined attribute
3. No, I'll give that a try. Must have missed that in the documentation. Will report back, thanks!

**Comment by JakeBooher** [comment] 2021-06-23 17:31
Adding the `'selectable' => false` seems to have resolved the issue, thanks!

What implications does setting `selectable` to false have?

**Comment by mfn** [comment] 2021-06-23 20:15
Good question. I'm not a fan or even user of SelectFields.

From my understanding, it starts with not including it in `SELECT` queries, whereas otherwise it would.

But what I don't quite understand, in your case you provided a custom `resolve` method, so why would it _still_ "go to the model" directly.

Maybe there's something fishy, maybe not.

If you will like and scout the tests, maybe there's a similar example or you can even reproduce it with a test, I'm happy to investigate/fix this.

**Comment by JakeBooher** [comment] 2021-06-23 21:08
Yeah, I can have a look into creating a reproduction case in the next couple days. It's entirely possible that there's something going on with my end as well as we use an extra abstraction we've created that makes some quality life of changes (mostly related to reusability that fits our use case specifically). I'll see about replicating it without that and check back soon!

**Comment by JakeBooher** [comment] 2021-06-23 21:22
Seems like it's not actually limited to just fields with a resolver, also happens on some direct field values that use non-scalar return types. For example:

`'changes' => ['type' => Type::listOf(\GraphQL::type('AuditLogChange'))],`

I get `Call to undefined method App\Models\AuditLog::changes()` since (I assume) it's assuming that I'm trying to load a relation

this just maps to a `changes` JSON column on the table (which is defined in `$casts` on my model as a JSON field). Setting ``selectable' => false` here resolves it as well

**Comment by JakeBooher** [comment] 2021-06-24 15:18
I've got a test case created here: https://github.com/JakeBooher/graphql-laravel-test

Should be able to pull it, run `composer install` and `php artisan test`

**Comment by mfn** [comment] 2021-07-02 19:05
Sorry, won't be able to look at this current (see https://github.com/rebing/graphql-laravel/discussions/800 )

**Comment by mfn** [comment] 2021-10-31 19:45
I checked out the project but when i then re-read your last comments, I've two observations:
- your original issue seems solved
- if you use a data structure like array (aka json) to represent sub-types, then yes, you also need to disable it being selected when you make use of `SelectFields`; otherwise it doesn't know it's not supposed to be a relation tries to load it.
  The problem is not accessing it but the automatic process assuming it needs to be loaded, which can't work.

Closing as I assume everything is answered; let me know if not!

**Closed by mfn** 2021-10-31 19:45 UTC
Labels: bug
